[profile.default]
src = "src"
out = "out"
libs = ["lib"]
allow_paths = ["./artifacts", "./lib/balancer-v3-monorepo"]

remappings = [
    "@balancer-labs/v3-solidity-utils/=lib/balancer-v3-monorepo/pkg/solidity-utils/",
    "@balancer-labs/v3-pool-utils/=lib/balancer-v3-monorepo/pkg/pool-utils/",
    "@balancer-labs/v3-interfaces/=lib/balancer-v3-monorepo/pkg/interfaces/",
    "@balancer-labs/v3-vault/=lib/balancer-v3-monorepo/pkg/vault/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/",
    "solady/=lib/solady/src/",
    "permit2/=lib/permit2/"
]